### ISSUE TITLE
Products Page

### ISSUE THREAD

**Issue by hamisirizwan** [SpaceyaTech/SYT-Web-Redesign#10]
- [ ] Hero Section
- [ ] Product Card
- [ ] Product Grid Section

**Comment by sonylomo** [comment]
Hey @hamisirizwan, I'd like to help out with this issue. 🙂

**Comment by hamisirizwan** [comment]
Hello @sonylomo The about page is available for taking. Please confirm with the designs and confirm if you can handle the about Us page so I can assign it to you

**Comment by hamisirizwan** [comment]
Awesome @sonylomo Kindly comment on the aboutUs issue so i can find your username.
