### ISSUE TITLE
Breaking `Community page` few seconds after loading. Dark/white theme toggle. Changing the state of the like button on blogs page

### ISSUE THREAD

**Issue by allanmathenge** [SpaceyaTech/SYT-Web-Redesign#116]
I am new to open source and this project in particular. I would like to improve on the following states of your application

1. Breaking community page a few seconds after loading. I am having a challenge using navigation bar to access the `Community` page section. It says "Unexpected Application Error! Invalid time value".

2. Implement the toggle button on "light" and "dark" theme. Using the inbuilt chrome light/dark theme is making the user miss important updates, the UI is not very user friendly on dark theme.

3. Was the thumbs up button on blogs page meant to change state as `like button`? I would recommend its subsequent change in state when i click  👍 to it.

**Comment by sonylomo** [comment]
Hey @allanmathenge, thank you for creating this issue 😌. Would you be interested in jumping on a call with me to discuss this issue some more?

We're always looking out for people willing to get into open source and I'm sure you can help us out a ton. 🙂

**Comment by allanmathenge** [comment]
YES. We can schedule a call. I'll be impressed.

**Comment by sonylomo** [comment]
What's your email address?

**Comment by allanmathenge** [comment]
***@***.***

**Comment by sonylomo** [comment]
Reach out to me via email (sonylomo1@gmail.com) so we can arrange a call.

**Comment by JimmyTron** [comment]
> Reach out to me via email ([sonylomo1@gmail.com](mailto:sonylomo1@gmail.com)) so we can arrange a call.

did this call happen?

**Comment by allanmathenge** [comment]
Yes, on Jan 27. I've been working on that.

**Comment by sonylomo** [comment]
@allanmathenge , are you still experiencing the breaking community page issue? 👀

**Comment by sonylomo** [comment]
1. the first issue has been addressed
2. the second issue is low priority at the moment and will not be addressed for now
3. the third issue will be addressed in a future website redesign sprint
