### ISSUE TITLE
Add a loading spinner for components with loading states

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#140]
## Description
Any instances of `isLoading` or `isPending` should have a `<Loader/>` component as part of it.
  ```jsx
import { Loader } from "../../../../../components";

  {isLoading && (
    <div className="flex flex-col items-center justify-center gap-4 py-10">
      <Loader />
      <p className="text-lg font-medium text-primary">Loading event...</p>
    </div>
  )}
  ```
 For reference, check out: `src/APP/pages/community/sections/eventsSection/SingleEvents/SingleEvent.jsx`

**Comment by zidanegimiga** [comment]
Is this issue still open?

**Comment by sonylomo** [comment]
This issue was resolved during the last sprint. ✅
