### ISSUE TITLE
Example .env file

### ISSUE THREAD

**Issue by nyandika** [SpaceyaTech/SYT-Web-Redesign#148]
It would be very good to have a .env.example file in the repo with sample values for all the key env variables used in the repo.
This would be quite useful for anyone starting to contribute and doesn't know of all the env variables present

e.g 

```
REACT_APP_API_BASE_URL='<API URL from backend>'
SERVICE_ID='<Vite service ID from blahblahblah>'
```

etc

**Comment by sonylomo** [comment]
Issues was addressed in last sprint ✅
