### ISSUE TITLE
Pick a testing framework

### ISSUE THREAD

**Issue by alvyynm** [SpaceyaTech/SYT-Web-Redesign#191]
A [recent commit](https://github.com/SpaceyaTech/SYT-Web-Redesign/commit/11e304a1e0f9add493c31f4be95cdaa90b15aad8) to the main branch has added a PR template. 

One of the requirements is to include tests when adding a new feature. However, it seems we haven't decided on an appropriate testing framework to be used. I suggest we settle on one to avoid conflicts in the future.

**Comment by alvyynm** [comment]
Thoughts? @sonylomo

**Comment by sonylomo** [comment]
Testing hasn't been a major priority because we were short handed.

However, I'm open to the idea. I'll do my research and we can settle on a testing tool to use. 🙂

**Comment by nyandika** [comment]
I haven't contributed in this space for what looks like eons but I had time today.

I have a pull request #193 testing this out.

I have gone with vitest for unit tests and playwright for end-to-end tests

please review and we can discuss merits and shortcomings of both and other alternatives

**Comment by sonylomo** [comment]
Thank you @nyandika for your contribution. 🙂
