### ISSUE TITLE
Admin Shop Pages: Dashboard Page

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#194]
## Description

Refer to [this Figma Design](https://www.figma.com/design/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?node-id=5494-10105&t=PNsF2qBBc3xyzFjV-0) for the Dashboard Page.

Please use [`Shadcn`](https://ui.shadcn.com/docs/components/data-table) for the Data Table and [`Recharts`](https://recharts.org/?p=/en-US/guide) for charts. Otherwise, please use Tailwind CSS styles.

## Tasks

- [ ] Implement the designs referenced above
- [ ] Make it responsive on mobile if possible

**Comment by sonylomo** [comment]
This issue was partially fixed by PR #199, however it still needs a lot of UI work and is still open to anyone who wants to complete the dashboard page.

**Comment by Avinashshiyani** [comment]
> Refer to [this Figma Design](https://www.figma.com/design/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?node-id=5494-10105&t=PNsF2qBBc3xyzFjV-0) for the Dashboard Page.
> 
> Please use [`Shadcn`](https://ui.shadcn.com/docs/components/data-table) for the Data Table and [`Recharts`](https://recharts.org/?p=/en-US/guide) for charts. Otherwise, please use Tailwind CSS styles.
> 
> ## Tasks
> * [ ]  Implement the designs referenced above
> * [ ]  Make it responsive on mobile if possible


# Dashboard Page Conversion Proposal

## Proposal Overview

Hello team,

I propose converting the Figma design to Tailwind CSS to ensure consistency and achieve a polished UI implementation. I'm ready to take on this task.

## Implementation Details

### Tools & Technologies:
- 🎨 **Figma**: Source of the original design.
- 🛠️ **Tailwind CSS**: Used for efficient and consistent UI development.

### Approach

1. **Conversion Strategy**: Translate Figma designs into Tailwind CSS utility classes for seamless integration.
   
2. **Responsive Design**: Implement responsive layouts using Tailwind CSS utilities for optimal viewing on all devices.

## Next Steps

I'm eager to proceed with this task and welcome your feedback or questions.

Best regards,  
Avinash

**Comment by sonylomo** [comment]
Hey @Avinashshiyani 👋🏾

As referenced in the comment, we already have Figma designs for the project and use TailwindCSS for implementation.

If you'd like to pick this issue up and implement the [referenced Figma design](https://www.figma.com/design/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?node-id=5494-10105&t=PNsF2qBBc3xyzFjV-0), we are more than happy to receive your contribution. 🙂

**Comment by Avinashshiyani** [comment]
> Hey @Avinashshiyani 👋🏾
> 
> As referenced in the comment, we already have Figma designs for the project and use TailwindCSS for implementation.
> 
> If you'd like to pick this issue up and implement the [referenced Figma design](https://www.figma.com/design/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?node-id=5494-10105&t=PNsF2qBBc3xyzFjV-0), we are more than happy to receive your contribution. 🙂

So thanks for giving me this chance @sonylomo and i am waiting for the asign for this role

**Comment by Avinashshiyani** [comment]
# Web Page Preview

Hi Team,

I've created a web page based on our Git repository and converted our Figma design into Tailwind CSS using React. You can check it out ⬇️

![screencapture-localhost-5173-admin-2024-06-25-20_48_11](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/107192407/328a9647-d867-427e-aca8-137ee40e0677)

Could you please take a look and let me know if it aligns with our vision? Specifically, I'd appreciate feedback on:
- **Design and layout**
- **Responsiveness across devices**
- **Integration of Figma design into the page**

Thanks a lot!

Best,
Avinash

**Comment by sonylomo** [comment]
> # Web Page Preview
> 
> Hi Team,
> 
> I've created a web page based on our Git repository and converted our Figma design into Tailwind CSS using React. You can check it out ⬇️
> 
> ![screencapture-localhost-5173-admin-2024-06-25-20_48_11](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/107192407/328a9647-d867-427e-aca8-137ee40e0677)
> 
> Could you please take a look and let me know if it aligns with our vision? Specifically, I'd appreciate feedback on:
> - **Design and layout**
> - **Responsiveness across devices**
> - **Integration of Figma design into the page**
> 
> Thanks a lot!
> 
> Best,
> Avinash
> 

I think you might have misunderstood the issue.

We DON'T need new Figma designs.

We WANT you to write ReactJS code to implement OUR Figma designs.

If that's what you've done, then please make a Pull Request to the `Dev` branch. 🙂

**Comment by Avinashshiyani** [comment]
> > # Web Page Preview
> > 
> > Hi Team,
> > 
> > I've created a web page based on our Git repository and converted our Figma design into Tailwind CSS using React. You can check it out ⬇️
> > 
> > ![screencapture-localhost-5173-admin-2024-06-25-20_48_11](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/107192407/328a9647-d867-427e-aca8-137ee40e0677)
> > 
> > Could you please take a look and let me know if it aligns with our vision? Specifically, I'd appreciate feedback on:
> > - **Design and layout**
> > - **Responsiveness across devices**
> > - **Integration of Figma design into the page**
> > 
> > Thanks a lot!
> > 
> > Best,
> > Avinash
> > 
> 
> I think you might have misunderstood the issue.
> 
> We DON'T need new Figma designs.
> 
> We WANT you to write ReactJS code to implement OUR Figma designs.
> 
> If that's what you've done, then please make a Pull Request to the `Dev` branch. 🙂

I have converted figma to react I just wanted the feedback that it's propely going or not 😅 it's react code only 😇. 
It's half done after fully done I will create a pull request.

**Comment by sonylomo** [comment]
You're doing great so far...keep going 😁🙌🏾💃🏾

![giphy](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/49971500/0cbf1032-3e7e-4cac-8647-399a98a3d20e)

**Comment by Avinashshiyani** [comment]
# :sparkles: Update on Figma to Tailwind Conversion :sparkles:

Hi @sonylomo 

Just wanted to share a quick update with you! :blush:

The **Figma to Tailwind conversion page** is almost ready. We're about **90%** done and are in the final stages of completion. :muscle:

![Progress Bar](https://progress-bar.dev/90)

Stay tuned for the finishing touches! :rocket:

Best regards,  
Avinash

---

If you have any questions or suggestions, feel free to drop a comment here. :point_down:
