### ISSUE TITLE
Linting and formatting checks are ever failing

### ISSUE THREAD

**Issue by alvyynm** [SpaceyaTech/SYT-Web-Redesign#212]
Since proper linting and formatting checks were added in #193, all of them have always failed. We should start addressing this. From build previews, the key issue we have is code formatting and linting (formatting is an easy fix but the latter requires a little bit of work to the codebase because it's manual). 

We have checks in place for both in `package.json`, and we need to start enforcing these standards before approving PRs. So before someone's PR is approved, they should, among other things, run the `prettier:format` and `lint` scripts in `package.json` (added in #193). 

That way, one gets a chance to fix these before blindly making a PR. We should also update the PR template to let everyone know while making a PR.

Tasks:

- [ ] Fix linting issues
- [ ] Fix formatting issues
- [ ] Update PR template

**Comment by alvyynm** [comment]
@sonylomo, @bridgitkanini, @Ase020, @JimmyTron what do you guys think?

**Comment by sonylomo** [comment]
As long as you're the one fixing it  😃

**Comment by alvyynm** [comment]
Yes, I'll work on it.
