### ISSUE TITLE
Convert Figma To React

### ISSUE THREAD

**Issue by Avinashshiyani** [SpaceyaTech/SYT-Web-Redesign#213]
# Proposal: Convert Figma Orders-report Page to React Component with Tailwind CSS

## Overview

Hello SYT-Web-Redesign,

I would like to convert the Orders-report page from Figma into a React component using Tailwind CSS. This will enhance our project's UI consistency and maintainability.

## Figma Design

[View Figma Design](https://www.figma.com/design/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?node-id=5494-10945&t=iXfeArXs7gJDgdf7-0)

## Implementation

- **Route Setup**:
    ```javascript
    {
        path: "/admin/shop/orders-report",
        element: <OrdersReport />, // Order Page to be built
    }
    ```

- **Component Development**:
    - Create `OrdersReport` React component.
    - Style with Tailwind CSS.

## Request for Task Assignment

Please assign this task to me. I'm confident in delivering a high-quality component.

Thank you!

Best regards,  
Avinash Shiyani

**Comment by sonylomo** [comment]
This page has already been assigned to someone else on issue #200
