### ISSUE TITLE
Add Contribution documentation

### ISSUE THREAD

**Issue by RichieMuga** [SpaceyaTech/SYT-Web-Redesign#226]
## Feat

- [ ] add contribution.md documentation.

**Comment by sonylomo** [comment]
Hey @RichieMuga, you can find the document [here](https://github.com/SpaceyaTech/SYT-Web-Redesign/blob/Dev/docs/CONTRIBUTING.md).

I realize it might be a bit hard to find for new contributors, so I'll move it to the root directory. 🙂

**Comment by RichieMuga** [comment]
Okey, thank you.
