### ISSUE TITLE
Tab logo

### ISSUE THREAD

**Issue by derrickgolden** [SpaceyaTech/SYT-Web-Redesign#41]
Change the logo displayed on the tab from that of Vite to SYT logo
![Screenshot 2023-08-23 125011](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/40804191/5c22e36f-32e9-4b17-b7d2-498e6ffc9b63)

**Comment by derrickgolden** [comment]
Hi, I could like to handle this issue? Tab logo #41

**Comment by sonylomo** [comment]
This issue was addressed on a different PR. 🙂
