### ISSUE TITLE
UI Fix: Home page

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#58]
The Home page has some inconsistency with the [Figma design](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=1113-7655&mode=design&t=v9HqbCbVkTBeXRdy-0). 

⭐️  The goal is to implement a UI that's as close to the Figma designs as possible for both mobile and desktop layouts. 

These are some examples (feel free to rectify fixes that haven't been highlighted 👇 ):

**Desktop view:**
![Image](https://user-images.githubusercontent.com/49971500/266938582-e2c2e18d-4b2b-491a-b23a-86baa87b50ee.png)

**Mobile view:**
![Image](https://user-images.githubusercontent.com/49971500/266940139-5c7830da-afdd-4078-905b-a50bb4b83224.png)

**Comment by davidkrupa** [comment]
@sonylomo
I can work on this. Please assign it to me.

**Comment by Oukomondi** [comment]
Hi @JimmyOty, @sonylomo and @davidkrupa. This landing page needs to be completely redone by the designers. I had raised similar issues including the hero section on the desktop view which needs to be a dark shade or something else, to make the logo visible. The achievements tracker needs to be redone and there are a lot of things missing on the landing page to completely tell a visitor what SYT is all about. If the landing page can be redone before deployment, it would be super.

**Comment by davidkrupa** [comment]
Hi @Oukomondi. I can help you with other issues. Will only the design of the home page be changed or will other pages be changed as well?

**Comment by Oukomondi** [comment]
The homepage and the resources page. But we shall start with the home page.

**Comment by sonylomo** [comment]
All the issues were addressed in a different PR.
