### ISSUE TITLE
UI fix: Products Page

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#60]
The Products page has some inconsistency with the [Figma design](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=1113-7655&mode=design&t=v9HqbCbVkTBeXRdy-0). 

⭐️  The goal is to implement a UI that's as close to the Figma designs as possible for both mobile and desktop layouts. 

These are some examples (feel free to rectify fixes that haven't been highlighted 👇 ):

**Desktop view:**

![Image](https://user-images.githubusercontent.com/49971500/266948160-138cae4a-3c18-4653-841f-f635cfb87c7d.png)

**Mobile view:**

Rectify text alignment:
![Image](https://user-images.githubusercontent.com/49971500/266948277-fba07d8b-5ce4-4c38-8fd2-2a06f475292d.png)

**Comment by Sky-De** [comment]
@sonylomo hi, please assign this to me, i would like to fix this for you
Thanks

**Comment by sonylomo** [comment]
hey @Sky-De, go for it! 🙂

**Comment by Sky-De** [comment]
@sonylomo i took a look at your figma design which you've shared, but 
1.there is not design for ourProduct section
2.there is diffrence between screen which you shared and your code while running

![1](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/79264045/968e6748-ea53-4f04-b549-d97b0ab104f5)
![2](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/79264045/7c3ce01d-8933-47bd-bcdb-fcdd186175ee)

also as there is no figma design for this section please clarify what you mean exactly of ( remve padding around text block) cuz there is h4, h2 and p tag in this section
thanks

**Comment by JimmyTron** [comment]
The figma design is available on the readme file.  Kindly check the file.

**Comment by sonylomo** [comment]
There was a design overhaul, therefore this issue is irrelevant.
