### ISSUE TITLE
UI fix: Donate Page

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#61]
The Donate page has some inconsistency with the [Figma design](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=1113-7655&mode=design&t=v9HqbCbVkTBeXRdy-0). 

⭐️  The goal is to implement a UI that's as close to the Figma designs as possible for both mobile and desktop layouts. 

These are some examples (feel free to rectify fixes that haven't been highlighted 👇 ):

 First, you can start by fixing spelling mistakes. 🙂

**Desktop view:**
The column cards are supposed to be 3 instead of 4.
![Image](https://user-images.githubusercontent.com/49971500/266953031-264ddb0a-cf27-4004-9392-6aad7f1e3a56.png)

**Mobile view:**

![Image](https://user-images.githubusercontent.com/49971500/266953948-ba2f8d4b-c071-48a4-8206-28ba394f9f39.png)

**Comment by davidkrupa** [comment]
@sonylomo
You can assign this task to me. I will fix this UI.

**Comment by sonylomo** [comment]
Have at it @davidkrupa 🙂
