### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by hamisirizwan** [SpaceyaTech/SYT-Web-Redesign#7]
- [x] #19
- [x] #18
- [x] #17

**Comment by Sky-De** [comment]
Do you have any designs for this or just want these three sections look better?

**Comment by JimmyTron** [comment]
@Sky-De check this discussion page for the design [Design](https://github.com/SpaceyaTech/SYT-Web-Redesign/discussions/15#discussion-5273609)

**Comment by sonylomo** [comment]
Some UI inconsistencies need to be rectified.

**Comment by sonylomo** [comment]
Closing this issue because the remaining work will be handled by #58.
