### ISSUE TITLE
MVP: Footer link fixes

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#73]
## Description

- Some links on the footer aren't linked to actual routes.
- For the MVP, we'll only need these pages on the navbar:
   - Home
   - About Us
   - Community

## Tasks

- [x] Add required routes to the footer links
- [x] Comment out footer links that are not required for the MVP

**Comment by Ase020** [comment]
Added social links to the footer

**Comment by Oukomondi** [comment]
We should review the changes made so far on Saturday night. A lot has been changed but the link that is visible to the public on Vercel is the link that was given by Rizwan months ago. Is there a staging branch or you guys are viewing it locally?
