### ISSUE TITLE
Navigate to the top of a page on navigation

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/SYT-Web-Redesign#74]
## Description

- Some links navigate to the bottom of the page when clicked. We want it to scroll to the top instead.

## Tasks

- [ ] Suggested fixes from [StackOverflow](https://stackoverflow.com/questions/70193712/how-to-scroll-to-top-on-route-change-with-react-router-dom-v6) using `useLocation` hook.

**Comment by octocatblain** [comment]
- requesting to work on this issue. Kindly assign me: @sonylomo @spaceyatech-org

**Comment by sonylomo** [comment]
Go for it @octocatblain 🙂

**Comment by octocatblain** [comment]
@sonylomo I cant find links that scroll to th bottom of the page as suggested in the issue. Can you kindly give me specifics on where I can find the big?

**Comment by sonylomo** [comment]
Hey @octocatblain, I apologize for the inconvenience. This issue was already addressed in another PR. However, it wasn't documented. I'm therefore going to close this issue as complete. 

You could take a look at other issues in the repo that you can help out with.

**Comment by octocatblain** [comment]
@sonylomo sure 💯 Will do.
