### ISSUE TITLE
Enforce Login on Admin Pages 

### ISSUE THREAD

**Issue by spaceyatech-org** [SpaceyaTech/SYT-Web-Redesign#88]
# Admin Pages Auth intergration

```https://spaceyatech.com/admin/events/add-event```

![image](https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/139357796/9c39ee0e-cdd0-456c-b3eb-0c0e60f895c9)

**Comment by sonylomo** [comment]
Login has been set up.
